apiVersion: v1
kind: Deployment
apiVersion: apps/v1
metadata:
  name: calico-policy
  namespace: kube-system
  labels:
    k8s-app: calico-policy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: calico-policy
  template:
    metadata:
      labels:
        k8s-app: calico-policy
        name: calico-policy
        version: latest
    spec:
      imagePullSecrets:
      - name: dntlpw
      hostNetwork: true
      restartPolicy: Always
      containers:
      - image: calico/kube-controllers:v2.0.0
        name: calico-policy
        env:
        - name: ETCD_ENDPOINTS
          value: "http://MASTER_HOSTNAME:2379"
        - name: K8S_API
          value: "https://kubernetes.default.svc.CLUSTER_DOMAIN:443"
        - name: CONFIGURE_ETC_HOSTS
          value: "false"
