{%- set encryptionKey = pillar['kubernetes']['master']['encryption-key'] -%}
kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: {{ encryptionKey }}
      - identity: {}
